#pragma once
enum T_Nodos {
	T_RAIZ = 0,
	T_TRANSFORM = 1,
	T_ROTACION = 2,
	T_ESCALADO = 3,
	T_TRASLACION = 4,
	T_MALLA = 5,
	T_LUZ = 6,
	T_SUNLIGHT = 7,
	T_POINTLIGHT = 8,
	T_FLASHLIGHT = 9,
	T_CAMARA = 10

};